### ISSUE TITLE
Adjustments for servers

### ISSUE THREAD

**Issue by hamadmarri** [hamadmarri/cachy-sched#10]
Todo:
1. Full support for cgroups, fair groups, autogroup
2. Variable time slice instead of preempt every tick
Any suggestions are appreciated

**Comment by arabcian** [comment]
We would love to see some numa compatibility, which affects both server and desktop usage. As config_numa=y is recommended for cpus later than 1st gen corei7

**Comment by hamadmarri** [comment]
Hi @arabcian ,

Can you please test this revision https://github.com/hamadmarri/cachy-sched/blob/master/patches/cachy/v5.8/cachy-5.8-r5.patch ?

Any feedback is appreciated 

Thanks
