### ISSUE TITLE
Freeze on cachy-5.8-r7

### ISSUE THREAD

**Issue by raykzhao** [hamadmarri/cachy-sched#13]
Hi. 

On both of my laptop and desktop machine, the cachy-5.8-r7 causes system freeze under heavy load e.g. compiling. Reverting the change of reset_lifetime at hamadmarri/linux@d45986942ebeed2a0827bbaa0edc2368611ebe4a seems to fix the problem on my system. 

Not sure whether it is relevant, I am using the voluntary preemption with the autogroup enabled.

Regards,
Raymond

**Comment by hamadmarri** [comment]
It's this line
```
u64 old_hrrn_x2	= life_time_x2 / se->vruntime;
```
Division by zero. se vruntime = 0 the time freezed 

I will fix this soon. It's weird that it never happened on my machine for about 3 days.

Fast fix:
try, go to kernel/sched/fair.c

Find reset_lifetime function
Change "/ se->vruntime" to
"/ (se->vruntime + 1)"

**Comment by hamadmarri** [comment]
[cachy-r7-fix1.zip](https://github.com/hamadmarri/cachy-sched/files/5355719/cachy-r7-fix1.zip)
Try this fix please

**Comment by hamadmarri** [comment]
https://github.com/hamadmarri/cachy-sched/blob/master/patches/v5.8/cachy-5.8-r7-fix1.patch

**Comment by raykzhao** [comment]
Thank you for the fix! I haven't yet encountered any freezes so far after applying cachy-5.8-r7-fix1.

**Comment by hamadmarri** [comment]
Hi @raykzhao ,

Please reopen the issue if something wrong happened again with r7.

Thank you
