### ISSUE TITLE
interactivity_factor is not tunable via sysctl

### ISSUE THREAD

**Issue by raykzhao** [hamadmarri/cachy-sched#17]
Hi @hamadmarri 

I just saw your new CacULE scheduler. There is a small bug in the patch that it is still using `#ifdef CONFIG_CACHY_SCHED` in the `sysctl.c` file and therefore the interactivity factor is not tunable via sysctl.

**Comment by hamadmarri** [comment]
Ops! I trusted sed on changing some folders forgot that sysctl.c is not under kernel/sched folder.
Sorry about that.

Problem is fixed in this commit: https://github.com/hamadmarri/cachy-sched/commit/ebb797375d696309060baf8ad13dc3e62e132906


Thank you @raykzhao
