### ISSUE TITLE
Nvidia crash

### ISSUE THREAD

**Issue by eXt73** [hamadmarri/cachy-sched#3]
Hi Hamad ... you're doing a great job, but there are problems with nvidia modules - it says exec is invalid and won't load the module:

soryy my fault - bad name of kernel - working great ;)

WOW ... Man, your work is brilliant - see equal - optimized kernel for Kabylake - first movie on your scheduler, second CFS - hope you can see the difference - nice load on all cores/threads - our NeteXt`73

https://www.dropbox.com/sh/0utb407a7j23aek/AAAJEWjL9kboC_sodX26HNJBa?dl=0

Best regards

Tomek

**Comment by hamadmarri** [comment]
Hi Tomek,

I am happy to see this comparison. I couldn't see any differences between the two. What is the optimized kernel for Kabylake? is it developed by Kabylake as well? 

Thank you
Hamad

**Comment by eXt73** [comment]
Hello Hamad   Forgive me for not writing back so far - but I have so much work now that I can barely make it: P Tomorrow and today I will try to write back substantively.   Best regards  Dnia 24 sierpnia 2020 22:56 Hamad Marri &lt;notifications@github.com&gt; napisał(a):   Hi Tomek,  I am happy to see this comparison. I couldn&#39;t see any differences between the two. What is the optimized kernel for Kabylake? is it developed by Kabylake as well?  Thank you   Hamad  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .
