### ISSUE TITLE
one chunk rejected

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [hamadmarri/cachy-sched#5]
Hi,

I copy the 5.8 patch in my kernel 5.8.3 root folder and run patch -p1
everything ok but one chunk rejected. here it is:

-- Makefile    2020-08-04 01:04:51.327366223 +1000
+++ linux-5.8-cachy/Makefile    2020-08-04 00:13:59.710682597 +1000
@@ -2,8 +2,8 @@
 VERSION = 5
 PATCHLEVEL = 8
 SUBLEVEL = 0
-EXTRAVERSION =
-NAME = Kleptomaniac Octopus
+EXTRAVERSION = -cachy
+NAME = Cachy

 # *DOCUMENTATION*
 # To see a list of typical targets execute "make help"

Thanks

**Comment by hamadmarri** [comment]
Hi Robert,

You can edit the Makefile manually by updating
 
EXTRAVERSION = 
NAME = Kleptomaniac Octopus

to
EXTRAVERSION = -cachy
NAME = Cachy

or you can just leave it as before, it is just to show the kernel version when selecting the kernel in grub booting.

Thanks

**Comment by ROBERT-MCDOWELL** [comment]
Hi Hamad,
ok thanks!
PS: my wite's name is also Sarah and she's also very very patient ;)

**Comment by ROBERT-MCDOWELL** [comment]
Hi Hamad,
ok thanks!
PS: my wite's name is also Sarah and she's also very very patient ;)

**Comment by ROBERT-MCDOWELL** [comment]
Hi Hamad,
ok thanks!
PS: my wite's name is also Sarah and she's also very very patient ;)

**Comment by ROBERT-MCDOWELL** [comment]
Hi Hamad,
ok thanks!
PS: my wite's name is also Sarah and she's also very very patient ;)

**Comment by ROBERT-MCDOWELL** [comment]
..
