### ISSUE TITLE
issue using qemu VM's

### ISSUE THREAD

**Issue by thor2002ro** [hamadmarri/cachy-sched#6]
first start nothing, but stopping and starting VM gets you

Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu0, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu1, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu2, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu3, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu4, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu5, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu6, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu7, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu8, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0
Aug 26 09:54:39 Tower kernel: SVM: kvm [21606]: vcpu9, guest rIP: 0xfffff853d6ef22f4 unimplemented wrmsr: 0xc0010115 data 0x0

**Comment by hamadmarri** [comment]
In my machine the qemu runs find with cachy. Are you on version 5.8.3?

It seems to me it is a kvm issue.

**Comment by thor2002ro** [comment]
Yes I'm on 5.8.3 with an zen cpu
I didn't say it didn't run fine.... It doesn't seam to have any issues despise the kernel messages

**Comment by hamadmarri** [comment]
Ok I will look at this issue next week. I am hoping it's not related to Fair_group missing feature.

**Comment by hamadmarri** [comment]
Could you please try this branch, I added autogroup, cgroups, fair_group support
https://github.com/hamadmarri/linux/tree/groups_numa

please let me know if this solve the issue

**Comment by hamadmarri** [comment]
Please try this patch
https://github.com/hamadmarri/cachy-sched/blob/master/patches/cachy/v5.8/cachy-5.8-r5.patch

Note: Enable Numa, and Cgroups, cachy now supports numa and cgroups

Please let me know if the issue is solved with this patch
