### ISSUE TITLE
cgroup fair

### ISSUE THREAD

**Issue by vopo** [hamadmarri/cachy-sched#9]
docker : mountpoint for cpu not found.

**Comment by hamadmarri** [comment]
Hi @vopo ,

Could you upload .config file?
What patch is used?

**Comment by sirlucjan** [comment]
If possible, enter the result of the command (on the cachy scheduler, of course): 

```
wc -l /sys/fs/cgroup/cpu/tasks
```

**Comment by hamadmarri** [comment]
Could you please try this branch, I added autogroup, cgroups, fair_group support
https://github.com/hamadmarri/linux/tree/groups_numa

**Comment by vopo** [comment]
https://github.com/xanmod/linux-cachy
https://sourceforge.net/projects/xanmod/files/experimental/cachy_cpu_sched/
i use  5.8.8-xanmod1-cachy , thank sirlucjan

wc -l /sys/fs/cgroup/cpu/tasks
218 /sys/fs/cgroup/cpu/tasks


https://github.com/hamadmarri/linux/tree/groups_numa
Everything looks like ok.
thanks for all you've done

wc -l /sys/fs/cgroup/cpu/tasks
212 /sys/fs/cgroup/cpu/tasks

**Comment by vopo** [comment]
> If possible, enter the result of the command (on the cachy scheduler, of course):
> 
> ```
> wc -l /sys/fs/cgroup/cpu/tasks
> ```

https://github.com/xanmod/linux-cachy
https://sourceforge.net/projects/xanmod/files/experimental/cachy_cpu_sched/
i use 5.8.8-xanmod1-cachy , thank sirlucjan

wc -l /sys/fs/cgroup/cpu/tasks
218 /sys/fs/cgroup/cpu/tasks

**Comment by vopo** [comment]
> Could you please try this branch, I added autogroup, cgroups, fair_group support
> https://github.com/hamadmarri/linux/tree/groups_numa

https://github.com/hamadmarri/linux/tree/groups_numa
Everything looks like ok.
thanks for all you've done

wc -l /sys/fs/cgroup/cpu/tasks
212 /sys/fs/cgroup/cpu/tasks
